<?php if(!defined('IN_GS')){ die('you cannot load this page directly.'); } $innov_settings = Innovation_Settings(); include('header.inc.php'); ?>
<div class="container-fluid bg-dark"><div class="row"><div class="col-12 col-md-3 p-3 p-md-5" style="background-image: url('data/uploads/resto - Copy.jpg');background-repeat: repeat;background-attachment: fixed;">
<h1 class="p-3 text-center bg-white" style="opacity:0.9;"><strong><a href="<?php get_site_url(); ?>" class="text-dark">My Resto</a></strong></h1><div class="row text-center"><a href="<?php get_site_url(); ?>/?id=menu-makanan" class="btn btn-light rounded p-3 text-center bg-white col-4 col-md-6 border border-trasparent" style="opacity:0.9;">
<img class="img-fluid" src="data/uploads/restoweb (1).png"/><br/><strong>Food</strong></a><a href="<?php get_site_url(); ?>/?id=menu-minuman" class="btn btn-light rounded p-3 text-center bg-white col-4 col-md-6 border border-trasparent" style="opacity:0.9;">
<img class="img-fluid" src="data/uploads/restoweb (3).png"/><br/><strong>Drink</strong></a><a href="<?php get_site_url(); ?>/?id=paket-menu" class="btn btn-light rounded p-3 text-center bg-white col-4 col-md-6 border border-trasparent" style="opacity:0.9;">
<img class="img-fluid" src="data/uploads/restoweb (2).png"/><br/><strong>Paket</strong></a><a href="<?php get_site_url(); ?>/?id=order-my-resto" class="btn btn-light rounded p-3 text-center bg-white col-4 col-md-6 border border-trasparent" style="opacity:0.9;">
<img class="img-fluid" src="data/uploads/order.png"/><br/><strong>Order</strong></a><a href="<?php get_site_url(); ?>/?id=reservation" class="btn btn-light rounded p-3 text-center bg-white col-4 col-md-6 border border-trasparent" style="opacity:0.9;">
<img class="img-fluid" src="data/uploads/waiters.png"/><br/><strong>Reservasi</strong></a><a href="<?php get_site_url(); ?>/?id=contact" class="btn btn-light rounded p-3 text-center bg-white col-4 col-md-6 border border-trasparent" style="opacity:0.9;">
<img class="img-fluid" src="data/uploads/restoweb (4).png"/><br/><strong>Contact</strong></a></div></div>
<div class="col-12 col-md-9 p-3 p-md-5 bg-dark text-white"><div class="container-fluid"><div class="row"><div class="col-12 col-md-8 text-center"><h3><strong><a class="text-white" href="<?php get_page_url(); ?>"><?php get_page_title(); ?></a></strong></h3></div><div class="col-12 col-md-4"><p class="text-center"><time datetime="<?php get_page_date('Y-m-d'); ?>" pubdate><?php get_page_date('F jS, Y'); ?></time></p></div></div>
<nav class="breadcrumb justify-content-center"><ol class="breadcrumb bg-dark text-light"><li class="breadcrumb-item"><a class="text-white" href="<?php get_site_url(); ?>">Home</a></li><li class="breadcrumb-item"><?php Innovation_Parent_Link(get_parent(FALSE)); ?> <b><?php get_page_clean_title(); ?></b></li><li class="breadcrumb-item"><a class="text-white" href="<?php get_site_url(); ?>" id="logo" ><?php get_site_name(); ?></a></li></ol></nav><div class="bg-white text-secondary shadow rounded p-3 p-md-5" style="opacity:0.9"><?php get_page_content(); ?></div></div></div></div></div><?php include('footer.inc.php'); ?>
